// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Models;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(BurgerContext))]
    [Migration("20241220132555_BurgerOrder")]
    partial class BurgerOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.BurgerOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BurgerOrders");
                });

            modelBuilder.Entity("webapi.Models.BurgerProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BurgerProducts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Image = "cheese.jpg",
                            Name = "Cheeseburger",
                            Price = 25.00m,
                            Type = "Burger"
                        },
                        new
                        {
                            Id = 2L,
                            Image = "dblcheese.jpg",
                            Name = "Double Cheeseburger",
                            Price = 40.00m,
                            Type = "Burger"
                        },
                        new
                        {
                            Id = 3L,
                            Image = "burger.jpg",
                            Name = "Hamburger",
                            Price = 20.00m,
                            Type = "Burger"
                        },
                        new
                        {
                            Id = 4L,
                            Image = "fries.jpg",
                            Name = "French fries",
                            Price = 15.00m,
                            Type = "Side Order"
                        },
                        new
                        {
                            Id = 5L,
                            Image = "water.jpg",
                            Name = "Sparkling Water",
                            Price = 10.00m,
                            Type = "Drink"
                        },
                        new
                        {
                            Id = 6L,
                            Image = "nukacola.jpg",
                            Name = "Nuka-Cola",
                            Price = 15.00m,
                            Type = "Drink"
                        },
                        new
                        {
                            Id = 7L,
                            Image = "nukaorange.jpg",
                            Name = "Nuka-Orange",
                            Price = 15.00m,
                            Type = "Drink"
                        });
                });

            modelBuilder.Entity("webapi.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BurgerOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("BurgerProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BurgerOrderId");

                    b.HasIndex("BurgerProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("webapi.Models.OrderItem", b =>
                {
                    b.HasOne("webapi.Models.BurgerOrder", "BurgerOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("BurgerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.BurgerProduct", "BurgerProduct")
                        .WithMany()
                        .HasForeignKey("BurgerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BurgerOrder");

                    b.Navigation("BurgerProduct");
                });

            modelBuilder.Entity("webapi.Models.BurgerOrder", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
